all:
  hosts:
    master:
      ansible_host: 10.0.1.80
    core-1:
      ansible_host: 10.0.1.4
    core-2:
      ansible_host: 10.0.1.98
  vars:
    ansible_user: hadoop  # 기본 사용자
    ansible_ssh_private_key_file: /home/hadoop/EC2_Key.pem
    ansible_python_interpreter: /usr/bin/python3